export const enCopy = {
  controls: {
    theme: 'Theme',
    language: 'Language',
    themeLabels: {
      light: 'Light',
      dark: 'Dark',
      system: 'Auto',
    },
    localeShort: {
      ko: 'KO',
      ja: 'JA',
      en: 'EN',
    },
  },
  common: {
    languageLabels: {
      ko: 'Korean',
      ja: 'Japanese',
      en: 'English',
      KO: 'Korean',
      JA: 'Japanese',
      EN: 'English',
    },
    sectionLabels: {
      title: 'Title',
      abstract: 'Abstract',
      introduction: 'Introduction',
      methods: 'Methods',
      results: 'Results',
      discussion: 'Discussion',
      conclusion: 'Conclusion',
    },
    styleLabels: {
      psychology_paper: 'Psychology Paper',
      communication_analysis: 'Communication Analysis',
      relationship_dynamics: 'Relationship Dynamics',
      sociology: 'Sociology',
      behavioral_science: 'Behavioral Science',
      computational_text: 'Computational Text',
      bioinformatics: 'Data Analysis',
      PSYCHOLOGY_PAPER: 'Psychology Paper',
      COMMUNICATION_ANALYSIS: 'Communication Analysis',
      RELATIONSHIP_DYNAMICS: 'Relationship Dynamics',
      SOCIOLOGY: 'Sociology',
      BEHAVIORAL_SCIENCE: 'Behavioral Science',
      COMPUTATIONAL_TEXT: 'Computational Text',
      BIOINFORMATICS: 'Data Analysis',
    },
    sentimentLabels: {
      positive: 'Positive',
      neutral: 'Neutral',
      negative: 'Negative',
      mixed: 'Mixed',
    },
  },
  home: {
    brandDescription: 'Korean AI for turning conversations into papers',
    nav: {
      home: 'Home',
      upload: 'Upload',
      overview: 'Overview',
    },
    heroKicker: 'KOREAN AI RESEARCH',
    heroTitle: 'ChatPaper',
    heroLeadTop: 'Conversations',
    heroLeadBottom: 'into papers',
    heroDescription: 'Turn KakaoTalk and AI chats into an academic draft.',
    primaryCta: 'Start',
    secondaryCta: 'Upload',
    plannedFlow: 'FLOW',
    modules: ['Upload', 'Analyze', 'Reader', 'Export'],
    features: [
      { title: 'Fast start', body: 'Upload once and generate a draft immediately.' },
      { title: 'Research dashboard', body: 'See topics and sentiment at a glance.' },
      { title: 'Journal reader', body: 'Read, refine, and export in one flow.' },
    ],
  },
  upload: {
    navTitle: 'ChatPaper',
    navDescription: 'AI that turns conversations into papers',
    heroKicker: 'UPLOAD',
    heroTitle: 'Start with upload.',
    heroDescription: 'Upload a conversation file and generation begins right away.',
    signals: [
      ['Input', 'KakaoTalk ZIP or text'],
      ['Output', 'Paper draft and reader'],
      ['Speed', 'Analyze right after upload'],
    ],
    formTitle: 'Upload',
    formDescription: 'Click or drag a file here. ZIP uploads extract only the chat text.',
    stateReady: 'Ready',
    stateDrop: 'Drop here',
    stateDropHint: 'Upload starts right away.',
    stateAddFile: 'Add file',
    stateAddHint: 'Click or drag',
    statusUploading: 'Uploading',
    statusAnalyzing: 'Analyzing',
    statusUploadingHint: 'Preparing the chat text and sending the file.',
    statusAnalyzingHint: 'Generating the paper draft.',
    submit: 'Analyze',
    retry: 'Retry',
    doneTitle: 'Draft ready',
    doneDescription: 'Open it in the reader now.',
    donePrimary: 'Open reader',
    doneSecondary: 'New upload',
    errors: {
      maxSize: (maxMb: number) => `Files must be ${Math.floor(maxMb / 1024)}GB or smaller.`,
      invalidType: 'Only .zip .txt .md .json files are supported.',
      zipMissingText: 'This ZIP does not contain a KakaoTalk .txt export file.',
      zipTooLarge: (maxMb: number) =>
        `The extracted chat text is larger than ${maxMb}MB. Upload the exported .txt file directly.`,
      zipExtractFailed: 'Could not extract the chat text from this ZIP file.',
      uploadFailed: 'Upload failed.',
      analyzeFailed: 'Analysis failed.',
      generic: 'Something went wrong.',
    },
  },
  result: {
    eyebrow: 'RESEARCH DASHBOARD',
    title: 'Analysis complete.',
    description: 'The key structure and insights are ready to review.',
    mixedLanguage: 'Mixed language',
    sectionsCountBadge: (count: number) => `${count} sections`,
    newUpload: 'New upload',
    nextStepLabel: 'NEXT',
    nextStepValue: 'Review in reader',
    nextStepHint: 'Check the structure, then export.',
    openReader: 'Open reader',
    metrics: {
      primaryLanguage: 'Primary language',
      writingStyle: 'Style',
      sectionCount: 'Sections',
      sentimentFlow: 'Sentiment flow',
      pending: 'Pending',
    },
    compositionTitle: 'Paper structure',
    compositionDescription: 'The reader follows this exact order.',
    languageDistributionTitle: 'Language mix',
    languageDistributionDescription: 'Detected language ratio from the source.',
    insights: {
      sentiment: {
        title: 'Sentiment flow',
        description: 'A quick view of emotional movement over time.',
        emptyTitle: 'Sentiment data pending',
        emptyDescription: 'This section appears when summaries are ready.',
        badge: (label: string, count: number) => `${label} ${count}`,
        segmentTitle: (index: number, label: string) => `Segment ${index}: ${label}`,
      },
      topics: {
        title: 'Topic clusters',
        description: 'Repeated themes gathered into one view.',
        emptyTitle: 'Topic data pending',
        emptyDescription: 'Topics appear here after extraction finishes.',
      },
      events: {
        title: 'Key events',
        description: 'Important moments to read first.',
        emptyTitle: 'Event summary pending',
        emptyDescription: 'Key events appear here after generation finishes.',
      },
    },
    exportStage: 'NEXT',
    exportTitle: 'Move into the document reader.',
    exportDescription: 'Review the paragraphs and section flow, then export.',
    exportCta: 'Open reader',
    loading: 'Loading the analysis...',
    loadingErrorTitle: 'Could not load the result.',
    loadingErrorBack: 'Go back',
    notFound: 'Result not found.',
    fetchFailed: 'Could not load the result.',
    noResult: 'No analysis result available.',
  },
  paper: {
    eyebrow: 'PAPER VIEW',
    untitled: 'Untitled paper',
    description: 'A document view designed for focused reading.',
    meta: {
      language: 'Language',
      style: 'Style',
      generatedAt: 'Generated',
    },
    ctas: {
      readFromStart: 'From top',
      backToResult: 'Result',
      newUpload: 'Upload',
    },
    metrics: {
      readableSections: 'Readable sections',
      readableSectionsHint: 'Only sections with content',
      paragraphs: 'Paragraphs',
      paragraphsHint: 'Across the full document',
      readingTime: 'Reading time',
      readingTimeHint: 'Calm reading estimate',
      layout: 'Layout',
      layoutValue: 'Journal',
      layoutHint: 'Focused document view',
    },
    sectionNav: {
      title: 'Sections',
      description: 'Jump directly to a section.',
      emptyTitle: 'No sections available.',
      emptyDescription: 'The table of contents appears when content exists.',
    },
    readingTips: {
      title: 'Reading tips',
      description: 'A faster path when you only need the essentials.',
      items: [
        'Start with the abstract and conclusion to grasp the full arc.',
        'Pair this view with the result dashboard for better context.',
        'On mobile, the section list stays easy to scan and tap.',
      ],
    },
    body: {
      title: 'Body',
      description: 'Spacing is tuned for long-form reading.',
      emptyTitle: 'No body content yet.',
      emptyDescription: 'This area fills once the generated paper is stored.',
      sectionPrefix: 'Section',
      paragraphUnit: (count: number) => `${count} paragraphs`,
    },
    readingMinutes: (minutes: number) => `${minutes} min`,
    countUnit: (count: number) => `${count}`,
  },
  export: {
    eyebrow: 'EXPORT',
    title: 'Export',
    description: 'Download, save as PDF, or copy the paper instantly.',
    chips: {
      text: 'TXT',
      pdf: 'PDF',
      copy: 'COPY',
    },
    actions: {
      download: 'Text',
      printing: 'Preparing PDF',
      print: 'Save PDF',
      copied: 'Copied',
      copy: 'Copy text',
    },
    note: 'PDF export opens in the browser print dialog.',
    copyError: 'Clipboard access is unavailable. Please use text download instead.',
  },
  signin: {
    eyebrow: 'ACCESS',
    title: 'Sign in to continue.',
    description: 'Upload, results, and the paper reader unlock after login.',
    points: ['Conversation upload', 'Result dashboard', 'Paper reader'],
    google: 'Continue with Google',
    divider: 'or',
    email: 'Email',
    password: 'Password',
    submit: 'Sign in with email',
    pending: 'Signing in',
    helper: 'Use an existing account and continue right away.',
    invalid: 'Check your email or password and try again.',
  },
} as const
