export const jaCopy = {
  controls: {
    theme: 'テーマ',
    language: '言語',
    themeLabels: {
      light: 'ライト',
      dark: 'ダーク',
      system: '自動',
    },
    localeShort: {
      ko: 'KO',
      ja: 'JA',
      en: 'EN',
    },
  },
  common: {
    languageLabels: {
      ko: '韓国語',
      ja: '日本語',
      en: '英語',
      KO: '韓国語',
      JA: '日本語',
      EN: '英語',
    },
    sectionLabels: {
      title: 'タイトル',
      abstract: '要旨',
      introduction: '序論',
      methods: '方法',
      results: '結果',
      discussion: '考察',
      conclusion: '結論',
    },
    styleLabels: {
      psychology_paper: '心理学論文',
      communication_analysis: 'コミュニケーション分析',
      relationship_dynamics: '関係性分析',
      sociology: '社会学',
      behavioral_science: '行動科学',
      computational_text: 'テキスト分析',
      bioinformatics: '情報分析型',
      PSYCHOLOGY_PAPER: '心理学論文',
      COMMUNICATION_ANALYSIS: 'コミュニケーション分析',
      RELATIONSHIP_DYNAMICS: '関係性分析',
      SOCIOLOGY: '社会学',
      BEHAVIORAL_SCIENCE: '行動科学',
      COMPUTATIONAL_TEXT: 'テキスト分析',
      BIOINFORMATICS: '情報分析型',
    },
    sentimentLabels: {
      positive: '肯定',
      neutral: '中立',
      negative: '否定',
      mixed: '混合',
    },
  },
  home: {
    brandDescription: '会話を論文に整える韓国語AI',
    nav: {
      home: 'ホーム',
      upload: 'アップロード',
      overview: '概要',
    },
    heroKicker: 'KOREAN AI RESEARCH',
    heroTitle: 'ChatPaper',
    heroLeadTop: '会話を',
    heroLeadBottom: '論文へ',
    heroDescription: 'KakaoTalk と AI の会話を学術文書の下書きに整えます。',
    primaryCta: '開始',
    secondaryCta: 'アップロード',
    plannedFlow: 'FLOW',
    modules: ['アップロード', '分析', 'リーダー', 'エクスポート'],
    features: [
      { title: 'すぐ始まる', body: 'ファイルを上げるだけで下書きが生成されます。' },
      { title: '研究ダッシュボード', body: '主題と感情の流れをひと目で見られます。' },
      { title: '文書リーダー', body: '読み直しから書き出しまで自然につながります。' },
    ],
  },
  upload: {
    navTitle: 'ChatPaper',
    navDescription: '会話を論文に整えるAI',
    heroKicker: 'UPLOAD',
    heroTitle: 'アップロードから始まります。',
    heroDescription: '会話ファイルを上げると分析と下書き生成がすぐ始まります。',
    signals: [
      ['入力', 'KakaoTalk ZIP またはテキスト'],
      ['出力', '論文下書きとリーダー'],
      ['速度', 'アップロード後すぐ分析'],
    ],
    formTitle: 'アップロード',
    formDescription: 'クリックまたはドラッグしてください。ZIPは会話 txt だけを抽出してアップロードします。',
    stateReady: '準備完了',
    stateDrop: 'ここにドロップ',
    stateDropHint: 'すぐアップロードを開始します。',
    stateAddFile: 'ファイル追加',
    stateAddHint: 'クリックまたはドラッグ',
    statusUploading: 'アップロード中',
    statusAnalyzing: '分析中',
    statusGenerating: '論文生成中',
    statusUploadingHint: '会話 txt を準備してからアップロードしています。',
    statusAnalyzingHint: '言語を検出して論文作業をキューに入れています。',
    statusGeneratingHint: '論文セクションを執筆中です。最大 2〜3 分かかります。',
    submit: '分析',
    retry: '再選択',
    doneTitle: '下書きの準備ができました。',
    doneDescription: 'リーダーでそのまま確認できます。',
    donePrimary: 'リーダーを開く',
    doneSecondary: '新規アップロード',
    errors: {
      maxSize: (maxMb: number) => `ファイルサイズは ${Math.floor(maxMb / 1024)}GB 以下である必要があります。`,
      invalidType: '.zip .txt .md .json のみアップロードできます。',
      zipMissingText: 'この ZIP には KakaoTalk の会話 txt ファイルがありません。',
      zipTooLarge: (maxMb: number) =>
        `抽出した会話 txt が ${maxMb}MB を超えているため、Vercel のアップロード上限を超えます。txt ファイルを直接アップロードしてください。`,
      zipExtractFailed: 'この ZIP から会話 txt を抽出できませんでした。',
      uploadFailed: 'アップロードに失敗しました。',
      analyzeFailed: '分析に失敗しました。',
      generic: 'エラーが発生しました。',
    },
  },
  result: {
    eyebrow: 'RESEARCH DASHBOARD',
    title: '分析が完了しました。',
    description: '構造と主要インサイトだけを素早く確認できるように整理しました。',
    mixedLanguage: '混合言語',
    sectionsCountBadge: (count: number) => `セクション ${count}`,
    newUpload: '新規アップロード',
    nextStepLabel: 'NEXT',
    nextStepValue: 'リーダー確認',
    nextStepHint: '段落と構成を見てからエクスポート',
    openReader: 'リーダーを開く',
    metrics: {
      primaryLanguage: '主要言語',
      writingStyle: 'スタイル',
      sectionCount: 'セクション数',
      sentimentFlow: '感情の流れ',
      pending: '準備中',
    },
    compositionTitle: '論文構成',
    compositionDescription: 'リーダーでも同じ順番で確認できます。',
    languageDistributionTitle: '言語分布',
    languageDistributionDescription: '会話から検出された言語比率です。',
    insights: {
      sentiment: {
        title: '感情の流れ',
        description: '区間ごとの感情変化を要約します。',
        emptyTitle: '感情データ準備中',
        emptyDescription: '追加要約が生成されるとここに表示されます。',
        badge: (label: string, count: number) => `${label} ${count}`,
        segmentTitle: (index: number, label: string) => `${index}区間 ${label}`,
      },
      topics: {
        title: 'トピック',
        description: '繰り返し現れる主題を整理します。',
        emptyTitle: 'トピック準備中',
        emptyDescription: '抽出が完了するとここに表示されます。',
      },
      events: {
        title: '主要イベント',
        description: '重要な文脈を先に読めます。',
        emptyTitle: 'イベント要約準備中',
        emptyDescription: 'イベント要約が生成されるとここに表示されます。',
      },
    },
    exportStage: 'NEXT',
    exportTitle: '文書リーダーに進んでください。',
    exportDescription: '段落とセクションの流れを確認してから書き出せます。',
    exportCta: 'リーダーを開く',
    loading: '結果を読み込んでいます...',
    loadingErrorTitle: '結果を読み込めませんでした。',
    loadingErrorBack: '戻る',
    notFound: '分析結果が見つかりません。',
    fetchFailed: '結果を読み込めませんでした。',
    noResult: '分析結果がありません。',
  },
  paper: {
    eyebrow: 'PAPER VIEW',
    untitled: '無題の文書',
    description: '読みやすい流れで整えた文書ビューです。',
    meta: {
      language: '言語',
      style: 'スタイル',
      generatedAt: '生成時刻',
    },
    ctas: {
      readFromStart: '最初から',
      backToResult: '結果',
      newUpload: 'アップロード',
    },
    metrics: {
      readableSections: '読めるセクション',
      readableSectionsHint: '内容があるセクションのみ',
      paragraphs: '段落数',
      paragraphsHint: '全体の段落基準',
      readingTime: '読了目安',
      readingTimeHint: '落ち着いて読む想定',
      layout: 'レイアウト',
      layoutValue: 'ジャーナル',
      layoutHint: '集中しやすい文書ビュー',
    },
    sectionNav: {
      title: 'セクション',
      description: 'すぐ移動できます。',
      emptyTitle: '表示できるセクションがありません。',
      emptyDescription: '本文が生成されると目次が表示されます。',
    },
    readingTips: {
      title: '読むヒント',
      description: '短時間で確認したいときの順番です。',
      items: [
        '要旨と結論から見ると全体の流れを早く把握できます。',
        '結果ダッシュボードと一緒に見ると文脈がつかみやすくなります。',
        'モバイルでも目次と本文を自然に行き来できます。',
      ],
    },
    body: {
      title: '本文',
      description: '段落間の余白を広めに取り、読みやすく整えました。',
      emptyTitle: '本文がまだありません。',
      emptyDescription: '分析結果が保存されるとここに表示されます。',
      sectionPrefix: 'セクション',
      paragraphUnit: (count: number) => `${count}段落`,
    },
    readingMinutes: (minutes: number) => `${minutes}分`,
    countUnit: (count: number) => `${count}`,
  },
  export: {
    eyebrow: 'EXPORT',
    title: 'エクスポート',
    description: 'ダウンロード、PDF 保存、コピーをすぐ実行できます。',
    chips: {
      text: 'TXT',
      pdf: 'PDF',
      copy: 'COPY',
    },
    actions: {
      download: 'テキスト',
      printing: 'PDF 準備中',
      print: 'PDF 保存',
      copied: 'コピー完了',
      copy: '本文コピー',
    },
    note: 'PDF はブラウザの印刷画面から保存されます。',
    copyError: 'コピー権限を利用できません。テキストダウンロードをご利用ください。',
  },
  signin: {
    eyebrow: 'ACCESS',
    title: '続行するにはログインしてください。',
    description: 'アップロード、結果確認、論文リーダーはログイン後に利用できます。',
    points: ['会話アップロード', '結果ダッシュボード', '論文リーダー'],
    google: 'Google で続行',
    divider: 'または',
    email: 'メール',
    password: 'パスワード',
    submit: 'メールでログイン',
    pending: 'ログイン中',
    helper: '既存アカウントですぐに続行できます。',
    invalid: 'メールまたはパスワードを確認してください。',
  },
} as const
