export const koCopy = {
  controls: {
    theme: '테마',
    language: '언어',
    themeLabels: {
      light: '라이트',
      dark: '다크',
      system: '자동',
    },
    localeShort: {
      ko: 'KO',
      ja: 'JA',
      en: 'EN',
    },
  },
  common: {
    languageLabels: {
      ko: '한국어',
      ja: '일본어',
      en: '영어',
      KO: '한국어',
      JA: '일본어',
      EN: '영어',
    },
    sectionLabels: {
      title: '제목',
      abstract: '초록',
      introduction: '서론',
      methods: '연구 방법',
      results: '결과',
      discussion: '논의',
      conclusion: '결론',
    },
    styleLabels: {
      psychology_paper: '심리학 논문',
      communication_analysis: '커뮤니케이션 분석',
      relationship_dynamics: '관계 역학',
      sociology: '사회학',
      behavioral_science: '행동과학',
      computational_text: '계산 텍스트 분석',
      bioinformatics: '정보 분석형',
      PSYCHOLOGY_PAPER: '심리학 논문',
      COMMUNICATION_ANALYSIS: '커뮤니케이션 분석',
      RELATIONSHIP_DYNAMICS: '관계 역학',
      SOCIOLOGY: '사회학',
      BEHAVIORAL_SCIENCE: '행동과학',
      COMPUTATIONAL_TEXT: '계산 텍스트 분석',
      BIOINFORMATICS: '정보 분석형',
    },
    sentimentLabels: {
      positive: '긍정',
      neutral: '중립',
      negative: '부정',
      mixed: '혼합',
    },
  },
  home: {
    brandDescription: '대화를 논문으로 정리하는 한국어 AI',
    nav: {
      home: '홈',
      upload: '업로드',
      overview: '개요',
    },
    heroKicker: 'KOREAN AI RESEARCH',
    heroTitle: 'ChatPaper',
    heroLeadTop: '대화를',
    heroLeadBottom: '논문으로',
    heroDescription: '카카오톡과 AI 대화를 학술 문서 초안으로 정리합니다.',
    primaryCta: '시작',
    secondaryCta: '업로드',
    plannedFlow: 'FLOW',
    modules: ['업로드', '분석', '리더', '내보내기'],
    features: [
      { title: '가볍게 시작', body: '파일만 올리면 바로 초안이 생성됩니다.' },
      { title: '연구형 대시보드', body: '주제와 감정 흐름을 한 화면에서 봅니다.' },
      { title: '문서형 리더', body: '읽고 정리하고 내보내기까지 이어집니다.' },
    ],
  },
  upload: {
    navTitle: 'ChatPaper',
    navDescription: '대화를 논문으로 정리하는 AI',
    heroKicker: 'UPLOAD',
    heroTitle: '업로드로 시작합니다.',
    heroDescription: '대화 파일을 올리면 분석과 초안 생성이 바로 이어집니다.',
    signals: [
      ['입력', '카카오톡 ZIP 또는 텍스트'],
      ['출력', '논문 초안과 리더'],
      ['속도', '업로드 후 바로 분석'],
    ],
    formTitle: '업로드',
    formDescription: '클릭하거나 드래그하세요. ZIP은 대화 txt만 추출해 업로드합니다.',
    stateReady: '준비 완료',
    stateDrop: '여기에 놓기',
    stateDropHint: '바로 업로드를 시작합니다.',
    stateAddFile: '파일 추가',
    stateAddHint: '클릭 또는 드래그',
    statusUploading: '업로드 중',
    statusAnalyzing: '분석 중',
    statusGenerating: '논문 생성 중',
    statusUploadingHint: '대화 txt를 준비한 뒤 업로드하고 있습니다.',
    statusAnalyzingHint: '언어를 감지하고 논문 작업을 시작합니다.',
    statusGeneratingHint: '논문 섹션을 작성하고 있습니다. 최대 2~3분 소요됩니다.',
    submit: '분석',
    retry: '다시',
    doneTitle: '초안 준비 완료',
    doneDescription: '이제 리더에서 바로 확인할 수 있습니다.',
    donePrimary: '리더 열기',
    doneSecondary: '새 업로드',
    errors: {
      maxSize: (maxMb: number) => `파일 크기는 ${Math.floor(maxMb / 1024)}GB 이하여야 합니다.`,
      invalidType: '.zip .txt .md .json 파일만 업로드할 수 있습니다.',
      zipMissingText: '이 ZIP 안에는 카카오톡 대화 txt 파일이 없습니다.',
      zipTooLarge: (maxMb: number) =>
        `추출된 대화 txt가 ${maxMb}MB를 넘어 Vercel 업로드 한도를 초과합니다. txt 파일만 직접 올려주세요.`,
      zipExtractFailed: '이 ZIP에서 대화 txt를 추출하지 못했습니다.',
      uploadFailed: '업로드에 실패했습니다.',
      analyzeFailed: '분석에 실패했습니다.',
      generic: '오류가 발생했습니다.',
    },
  },
  result: {
    eyebrow: 'RESEARCH DASHBOARD',
    title: '분석이 완료되었습니다.',
    description: '핵심 구조와 인사이트만 빠르게 확인할 수 있도록 정리했습니다.',
    mixedLanguage: '혼합 언어',
    sectionsCountBadge: (count: number) => `섹션 ${count}개`,
    newUpload: '새 업로드',
    nextStepLabel: '다음',
    nextStepValue: '리더 검토',
    nextStepHint: '문단과 구성을 확인한 뒤 내보내기',
    openReader: '리더 열기',
    metrics: {
      primaryLanguage: '주 언어',
      writingStyle: '스타일',
      sectionCount: '섹션 수',
      sentimentFlow: '감정 흐름',
      pending: '준비 중',
    },
    compositionTitle: '논문 구성',
    compositionDescription: '리더에서 같은 순서로 확인할 수 있습니다.',
    languageDistributionTitle: '언어 분포',
    languageDistributionDescription: '대화에서 감지된 언어 비율입니다.',
    insights: {
      sentiment: {
        title: '감정 흐름',
        description: '구간별 정서 변화를 요약합니다.',
        emptyTitle: '감정 데이터 준비 중',
        emptyDescription: '추가 요약이 생성되면 여기에 표시됩니다.',
        badge: (label: string, count: number) => `${label} ${count}`,
        segmentTitle: (index: number, label: string) => `${index}구간 ${label}`,
      },
      topics: {
        title: '주제 묶음',
        description: '반복된 핵심 주제를 정리합니다.',
        emptyTitle: '주제 데이터 준비 중',
        emptyDescription: '주제 추출이 완료되면 여기에 표시됩니다.',
      },
      events: {
        title: '핵심 사건',
        description: '중요한 맥락을 먼저 읽을 수 있습니다.',
        emptyTitle: '사건 요약 준비 중',
        emptyDescription: '이벤트 요약이 생성되면 여기에 표시됩니다.',
      },
    },
    exportStage: 'NEXT',
    exportTitle: '이제 문서형 리더로 넘어가세요.',
    exportDescription: '문단과 섹션 흐름을 확인한 뒤 바로 내보낼 수 있습니다.',
    exportCta: '리더 열기',
    loading: '결과를 불러오는 중입니다...',
    loadingErrorTitle: '결과를 불러오지 못했습니다.',
    loadingErrorBack: '뒤로 가기',
    notFound: '분석 결과를 찾을 수 없습니다.',
    fetchFailed: '결과를 불러오지 못했습니다.',
    noResult: '분석 결과가 없습니다.',
  },
  paper: {
    eyebrow: 'PAPER VIEW',
    untitled: '제목 없는 문서',
    description: '읽기 흐름에 맞춰 정리된 문서형 뷰입니다.',
    meta: {
      language: '언어',
      style: '스타일',
      generatedAt: '생성 시각',
    },
    ctas: {
      readFromStart: '처음부터',
      backToResult: '결과',
      newUpload: '업로드',
    },
    metrics: {
      readableSections: '읽을 섹션',
      readableSectionsHint: '내용이 있는 섹션만 표시',
      paragraphs: '문단 수',
      paragraphsHint: '전체 문단 기준',
      readingTime: '예상 시간',
      readingTimeHint: '차분히 읽는 기준',
      layout: '레이아웃',
      layoutValue: '저널형',
      layoutHint: '집중형 문서 뷰',
    },
    sectionNav: {
      title: '섹션',
      description: '바로 이동할 수 있습니다.',
      emptyTitle: '표시할 섹션이 없습니다.',
      emptyDescription: '본문이 생성되면 목차가 나타납니다.',
    },
    readingTips: {
      title: '읽기 팁',
      description: '짧게 훑고 싶을 때 먼저 보는 순서입니다.',
      items: [
        '초록과 결론부터 보면 전체 흐름을 빠르게 파악할 수 있습니다.',
        '결과 대시보드와 함께 보면 맥락 이해가 더 쉬워집니다.',
        '모바일에서도 목차와 본문을 자연스럽게 오갈 수 있습니다.',
      ],
    },
    body: {
      title: '본문',
      description: '문단 간격을 넉넉하게 두어 읽기 편하게 구성했습니다.',
      emptyTitle: '본문이 아직 없습니다.',
      emptyDescription: '분석 결과가 저장되면 여기에 표시됩니다.',
      sectionPrefix: '섹션',
      paragraphUnit: (count: number) => `${count}문단`,
    },
    readingMinutes: (minutes: number) => `${minutes}분`,
    countUnit: (count: number) => `${count}개`,
  },
  export: {
    eyebrow: 'EXPORT',
    title: '내보내기',
    description: '다운로드, PDF 저장, 복사를 바로 진행할 수 있습니다.',
    chips: {
      text: 'TXT',
      pdf: 'PDF',
      copy: 'COPY',
    },
    actions: {
      download: '텍스트',
      printing: 'PDF 준비 중',
      print: 'PDF 저장',
      copied: '복사 완료',
      copy: '본문 복사',
    },
    note: 'PDF는 브라우저 인쇄 창에서 저장됩니다.',
    copyError: '복사 권한을 사용할 수 없습니다. 텍스트 다운로드를 이용해 주세요.',
  },
  signin: {
    eyebrow: 'ACCESS',
    title: '계속하려면 로그인하세요.',
    description: '업로드, 결과 확인, 논문 리더는 로그인 후 이어집니다.',
    points: ['대화 업로드', '결과 대시보드', '논문 리더'],
    google: 'Google로 계속',
    divider: '또는',
    email: '이메일',
    password: '비밀번호',
    submit: '이메일로 로그인',
    pending: '로그인 중',
    helper: '테스트 계정이나 기존 계정으로 바로 이어갈 수 있습니다.',
    invalid: '이메일 또는 비밀번호를 확인해 주세요.',
  },
} as const
